stack=[]
stack.append('a')
stack.append('b')
stack.append('c')
print('Initial Stack')
print(stack)
print('\nElement popped from stack :')
print(stack.pop())
print(stack.pop())
print(stack)
print('\nStack after elements are popped :')
print(stack)
